# 应用服务 WEB 相关配置
server:
  port: 8080
  servlet:
    context-path: /mympsamples

  #虚拟项目名  上下文根
  #server.servlet.context-path=/MisPosReports

spring:
  application:
    name: my-mp-samples
  profiles:
    active: test