spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sd_mis?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource

#  redis:
#    host: localhost # Redis服务器地址
#    database: 0 # Redis数据库索引（默认为0）
#    port: 6379 # Redis服务器连接端口
#    password: # Redis服务器连接密码（默认为空）
#    timeout: 3000ms # 连接超时时间（毫秒）

#logging:
#  level:
#    root: info
#    com.macro.mall: debug